name: Cactus Rock Content Marketing
favicon: null
layout_spectrum: 0.42207
typography_spectrum: 0.29451
title: Cactus Rock New Media Ltd.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffff8'
    - '#4481c4'
    - '#0f1509'
    - '#324353'
    - '#7fc8f1'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
