name: Cactus Rock Content Marketing
favicon: null
layout_spectrum: 0.43927679443731904
typography_spectrum: 0.25572698446922004
title: Cactus Rock New Media Ltd.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010300'
    - '#d40000'
    - '#739dcf'
    - '#fafcf9'
    - '#806f77'
  brandStrength: 0.5
  lightness: 0.8193056932650506
  saturation: 0.375
  rhythmicContrast: 0.6838147677481174
purpose: []
